# Checked in CI by cargo-deny: advisories, licenses, duplicate crates and sources.

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "MPL-2.0", "Unicode-3.0"]

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
